id: I721F36F4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T07:49:47+00:00'
last_modified: '2022-06-08T05:04:55.942458+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1130
  title: གསུང་ཐོར་བུ། ཀུན་དགའ་གྲོལ་མཆོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9303':
      image_group_id: I1CZ1394
      title: ''
      total_pages: 452
      order: 1
      base_file: 9303.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
