id: P005582
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 12:04:32.014130
source_metadata:
  id: bdr:W1CZ1130
  title: གསུང་ཐོར་བུ། ཀུན་དགའ་གྲོལ་མཆོག
  author: ''
  volumes:
    491e57da8a4a42bfbd97270c00b8cb15:
      image_group_id: I1CZ1394
      title: ''
      volume_number: 1
      total_pages: 452
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
